### ISSUE TITLE
RequireBin link: No index.js in this gist

### ISSUE THREAD

**Issue by mbonaci** [Level/leveldb.org#20]
![image](https://cloud.githubusercontent.com/assets/497926/5495358/364ccf8e-86fd-11e4-8e30-651fabc2447c.png)

**Comment by 75lb** [comment]
here's a working Requirebin link using the gist from above:
http://requirebin.com/?gist=brycebaril/9573685

however, it threw this error hashtag sad face.. 
```
Bundling error: 

Error: CORS request rejected: https://wzrd.in/multi
```
