### ISSUE TITLE
CI email address

### ISSUE THREAD

**Issue by vweevers** [Level/leveldb.org#31]
Bus factor and all, it'd be nice to have a appveyor@leveldb.org address. For the AppVeyor org account and GitHub machine user. Or perhaps a generic ci@leveldb.org.

Continuing from https://github.com/Level/leveldown/pull/309#issuecomment-255047863 by @0x00A:

> I do maintain that domain, any ideas for setting up email that we could all access? There might be something better than me adding it to my Google Apps account.

@ralphtheninja @juliangruber ideas?

**Comment by juliangruber** [comment]
don't know a free account, but we could send it to `ci-leveldb@gmail.com` or something which could be set up to forward

**Comment by vweevers** [comment]
Created a gmail, who wants the login details? I'll sharelock it. You can then add yourself to the forwarding list.

**Comment by vweevers** [comment]
Also found [MailGun](https://www.mailgun.com/), which does forwarding of 10k emails / month for free, with a custom domain. But for this purpose - account recovery and infrequent automated emails (I disabled most notifications) - gmail is just fine.

**Comment by ralphtheninja** [comment]
> Created a gmail, who wants the login details?

@vweevers Sure! I'm not familiar with sharelock though.

**Comment by vweevers** [comment]
@ralphtheninja or keybase?

**Comment by ralphtheninja** [comment]
@vweevers We could try that. Haven't used it in ages so had to reset account etc. Seems anyone I followed or someone following me was removed completely, oh well. https://keybase.io/ralphtheninja

**Comment by vweevers** [comment]
Sent :)
